export interface CittaInfo {
  nome: string;
  cap: string;
  provincia: string;
}

export const CITTA_ITALIANE: CittaInfo[] = [
  { nome: "Roma", cap: "00100", provincia: "RM" },
  { nome: "Milano", cap: "20100", provincia: "MI" },
  { nome: "Napoli", cap: "80100", provincia: "NA" },
  { nome: "Torino", cap: "10100", provincia: "TO" },
  { nome: "Palermo", cap: "90100", provincia: "PA" },
  { nome: "Genova", cap: "16100", provincia: "GE" },
  { nome: "Bologna", cap: "40100", provincia: "BO" },
  { nome: "Firenze", cap: "50100", provincia: "FI" },
  { nome: "Bari", cap: "70100", provincia: "BA" },
  { nome: "Catania", cap: "95100", provincia: "CT" },
  { nome: "Venezia", cap: "30100", provincia: "VE" },
  { nome: "Verona", cap: "37100", provincia: "VR" },
  { nome: "Messina", cap: "98100", provincia: "ME" },
  { nome: "Padova", cap: "35100", provincia: "PD" },
  { nome: "Trieste", cap: "34100", provincia: "TS" },
  { nome: "Taranto", cap: "74100", provincia: "TA" },
  { nome: "Brescia", cap: "25100", provincia: "BS" },
  { nome: "Parma", cap: "43100", provincia: "PR" },
  { nome: "Prato", cap: "59100", provincia: "PO" },
  { nome: "Modena", cap: "41100", provincia: "MO" },
  { nome: "Reggio Calabria", cap: "89100", provincia: "RC" },
  { nome: "Reggio Emilia", cap: "42100", provincia: "RE" },
  { nome: "Perugia", cap: "06100", provincia: "PG" },
  { nome: "Livorno", cap: "57100", provincia: "LI" },
  { nome: "Ravenna", cap: "48100", provincia: "RA" },
  { nome: "Cagliari", cap: "09100", provincia: "CA" },
  { nome: "Foggia", cap: "71100", provincia: "FG" },
  { nome: "Rimini", cap: "47900", provincia: "RN" },
  { nome: "Salerno", cap: "84100", provincia: "SA" },
  { nome: "Ferrara", cap: "44100", provincia: "FE" },
  { nome: "Sassari", cap: "07100", provincia: "SS" },
  { nome: "Latina", cap: "04100", provincia: "LT" },
  { nome: "Giugliano in Campania", cap: "80014", provincia: "NA" },
  { nome: "Monza", cap: "20900", provincia: "MB" },
  { nome: "Siracusa", cap: "96100", provincia: "SR" },
  { nome: "Pescara", cap: "65100", provincia: "PE" },
  { nome: "Bergamo", cap: "24100", provincia: "BG" },
  { nome: "Forlì", cap: "47100", provincia: "FC" },
  { nome: "Trento", cap: "38100", provincia: "TN" },
  { nome: "Vicenza", cap: "36100", provincia: "VI" },
  { nome: "Terni", cap: "05100", provincia: "TR" },
  { nome: "Bolzano", cap: "39100", provincia: "BZ" },
  { nome: "Bozen", cap: "39100", provincia: "BZ" },
  { nome: "Novara", cap: "28100", provincia: "NO" },
  { nome: "Piacenza", cap: "29100", provincia: "PC" },
  { nome: "Ancona", cap: "60100", provincia: "AN" },
  { nome: "Andria", cap: "76123", provincia: "BT" },
  { nome: "Arezzo", cap: "52100", provincia: "AR" },
  { nome: "Udine", cap: "33100", provincia: "UD" },
  { nome: "Cesena", cap: "47521", provincia: "FC" },
  { nome: "Lecce", cap: "73100", provincia: "LE" },
  { nome: "Pesaro", cap: "61121", provincia: "PU" },
  { nome: "Barletta", cap: "76121", provincia: "BT" },
  { nome: "Alessandria", cap: "15121", provincia: "AL" },
  { nome: "La Spezia", cap: "19100", provincia: "SP" },
  { nome: "Pisa", cap: "56100", provincia: "PI" },
  { nome: "Catanzaro", cap: "88100", provincia: "CZ" },
  { nome: "Lucca", cap: "55100", provincia: "LU" },
  { nome: "Brindisi", cap: "72100", provincia: "BR" },
  { nome: "Treviso", cap: "31100", provincia: "TV" },
  { nome: "Como", cap: "22100", provincia: "CO" },
  { nome: "Busto Arsizio", cap: "21052", provincia: "VA" },
  { nome: "Marsala", cap: "91025", provincia: "TP" },
  { nome: "Grosseto", cap: "58100", provincia: "GR" },
  { nome: "Varese", cap: "21100", provincia: "VA" },
  { nome: "Caserta", cap: "81100", provincia: "CE" },
  { nome: "Asti", cap: "14100", provincia: "AT" },
  { nome: "Sesto San Giovanni", cap: "20099", provincia: "MI" },
  { nome: "Ragusa", cap: "97100", provincia: "RG" },
  { nome: "Cremona", cap: "26100", provincia: "CR" },
  { nome: "Pavia", cap: "27100", provincia: "PV" },
  { nome: "Cosenza", cap: "87100", provincia: "CS" },
  { nome: "L'Aquila", cap: "67100", provincia: "AQ" },
  { nome: "Potenza", cap: "85100", provincia: "PZ" },
  { nome: "Campobasso", cap: "86100", provincia: "CB" },
  { nome: "Aosta", cap: "11100", provincia: "AO" },
  { nome: "Mantova", cap: "46100", provincia: "MN" },
  { nome: "Massa", cap: "54100", provincia: "MS" },
  { nome: "Carrara", cap: "54033", provincia: "MS" },
  { nome: "Cuneo", cap: "12100", provincia: "CN" },
  { nome: "Savona", cap: "17100", provincia: "SV" },
  { nome: "Imperia", cap: "18100", provincia: "IM" },
  { nome: "Belluno", cap: "32100", provincia: "BL" },
  { nome: "Rovigo", cap: "45100", provincia: "RO" },
  { nome: "Pordenone", cap: "33170", provincia: "PN" },
  { nome: "Gorizia", cap: "34170", provincia: "GO" },
  { nome: "Macerata", cap: "62100", provincia: "MC" },
  { nome: "Fermo", cap: "63900", provincia: "FM" },
  { nome: "Ascoli Piceno", cap: "63100", provincia: "AP" },
  { nome: "Teramo", cap: "64100", provincia: "TE" },
  { nome: "Chieti", cap: "66100", provincia: "CH" },
  { nome: "Rieti", cap: "02100", provincia: "RI" },
  { nome: "Viterbo", cap: "01100", provincia: "VT" },
  { nome: "Frosinone", cap: "03100", provincia: "FR" },
  { nome: "Isernia", cap: "86170", provincia: "IS" },
  { nome: "Benevento", cap: "82100", provincia: "BN" },
  { nome: "Avellino", cap: "83100", provincia: "AV" },
  { nome: "Matera", cap: "75100", provincia: "MT" },
  { nome: "Crotone", cap: "88900", provincia: "KR" },
  { nome: "Vibo Valentia", cap: "89900", provincia: "VV" },
  { nome: "Trapani", cap: "91100", provincia: "TP" },
  { nome: "Agrigento", cap: "92100", provincia: "AG" },
  { nome: "Caltanissetta", cap: "93100", provincia: "CL" },
  { nome: "Enna", cap: "94100", provincia: "EN" },
  { nome: "Nuoro", cap: "08100", provincia: "NU" },
  { nome: "Oristano", cap: "09170", provincia: "OR" },
  { nome: "Sud Sardegna", cap: "09048", provincia: "SU" },
  { nome: "Carbonia", cap: "09013", provincia: "SU" },
  { nome: "Iglesias", cap: "09016", provincia: "SU" },
  { nome: "Biella", cap: "13900", provincia: "BI" },
  { nome: "Verbania", cap: "28922", provincia: "VB" },
  { nome: "Vercelli", cap: "13100", provincia: "VC" },
  { nome: "Sondrio", cap: "23100", provincia: "SO" },
  { nome: "Lodi", cap: "26900", provincia: "LO" },
  { nome: "Lecco", cap: "23900", provincia: "LC" },
  { nome: "Pistoia", cap: "51100", provincia: "PT" },
  { nome: "Siena", cap: "53100", provincia: "SI" },
  { nome: "Cortina d'Ampezzo", cap: "32043", provincia: "BL" },
  { nome: "Merano", cap: "39012", provincia: "BZ" },
  { nome: "Meran", cap: "39012", provincia: "BZ" },
  { nome: "Bressanone", cap: "39042", provincia: "BZ" },
  { nome: "Brixen", cap: "39042", provincia: "BZ" },
  { nome: "Brunico", cap: "39031", provincia: "BZ" },
  { nome: "Bruneck", cap: "39031", provincia: "BZ" },
  { nome: "Rovereto", cap: "38068", provincia: "TN" },
  { nome: "Riva del Garda", cap: "38066", provincia: "TN" },
  { nome: "Conegliano", cap: "31015", provincia: "TV" },
  { nome: "San Donà di Piave", cap: "30027", provincia: "VE" },
  { nome: "Mestre", cap: "30170", provincia: "VE" },
  { nome: "Marghera", cap: "30175", provincia: "VE" },
  { nome: "Chioggia", cap: "30015", provincia: "VE" },
  { nome: "Jesolo", cap: "30016", provincia: "VE" },
  { nome: "Bassano del Grappa", cap: "36061", provincia: "VI" },
  { nome: "Schio", cap: "36015", provincia: "VI" },
  { nome: "Legnago", cap: "37045", provincia: "VR" },
  { nome: "San Bonifacio", cap: "37047", provincia: "VR" },
  { nome: "Villafranca di Verona", cap: "37069", provincia: "VR" },
  { nome: "Este", cap: "35042", provincia: "PD" },
  { nome: "Cittadella", cap: "35013", provincia: "PD" },
  { nome: "Abano Terme", cap: "35031", provincia: "PD" },
  { nome: "Montebelluna", cap: "31044", provincia: "TV" },
  { nome: "Castelfranco Veneto", cap: "31033", provincia: "TV" },
  { nome: "Vittorio Veneto", cap: "31029", provincia: "TV" },
  { nome: "Sacile", cap: "33077", provincia: "PN" },
  { nome: "Monfalcone", cap: "34074", provincia: "GO" },
  { nome: "Cividale del Friuli", cap: "33043", provincia: "UD" },
  { nome: "Tolmezzo", cap: "33028", provincia: "UD" },
  { nome: "Imola", cap: "40026", provincia: "BO" },
  { nome: "Faenza", cap: "48018", provincia: "RA" },
  { nome: "Lugo", cap: "48022", provincia: "RA" },
  { nome: "Carpi", cap: "41012", provincia: "MO" },
  { nome: "Sassuolo", cap: "41049", provincia: "MO" },
  { nome: "Mirandola", cap: "41037", provincia: "MO" },
  { nome: "Scandiano", cap: "42019", provincia: "RE" },
  { nome: "Correggio", cap: "42015", provincia: "RE" },
  { nome: "Fidenza", cap: "43036", provincia: "PR" },
  { nome: "Fiorenzuola d'Arda", cap: "29017", provincia: "PC" },
  { nome: "Riccione", cap: "47838", provincia: "RN" },
  { nome: "Cattolica", cap: "47841", provincia: "RN" },
  { nome: "Bellaria-Igea Marina", cap: "47814", provincia: "RN" },
  { nome: "Viareggio", cap: "55049", provincia: "LU" },
  { nome: "Forte dei Marmi", cap: "55042", provincia: "LU" },
  { nome: "Pietrasanta", cap: "55045", provincia: "LU" },
  { nome: "Camaiore", cap: "55041", provincia: "LU" },
  { nome: "Pontedera", cap: "56025", provincia: "PI" },
  { nome: "San Miniato", cap: "56028", provincia: "PI" },
  { nome: "Empoli", cap: "50053", provincia: "FI" },
  { nome: "Scandicci", cap: "50018", provincia: "FI" },
  { nome: "Sesto Fiorentino", cap: "50019", provincia: "FI" },
  { nome: "Campi Bisenzio", cap: "50013", provincia: "FI" },
  { nome: "Montecatini Terme", cap: "51016", provincia: "PT" },
  { nome: "Pescia", cap: "51017", provincia: "PT" },
  { nome: "San Gimignano", cap: "53037", provincia: "SI" },
  { nome: "Montepulciano", cap: "53045", provincia: "SI" },
  { nome: "Chianciano Terme", cap: "53042", provincia: "SI" },
  { nome: "Cortona", cap: "52044", provincia: "AR" },
  { nome: "Sansepolcro", cap: "52037", provincia: "AR" },
  { nome: "Città di Castello", cap: "06012", provincia: "PG" },
  { nome: "Foligno", cap: "06034", provincia: "PG" },
  { nome: "Spoleto", cap: "06049", provincia: "PG" },
  { nome: "Assisi", cap: "06081", provincia: "PG" },
  { nome: "Gubbio", cap: "06024", provincia: "PG" },
  { nome: "Orvieto", cap: "05018", provincia: "TR" },
  { nome: "Civitavecchia", cap: "00053", provincia: "RM" },
  { nome: "Fiumicino", cap: "00054", provincia: "RM" },
  { nome: "Tivoli", cap: "00019", provincia: "RM" },
  { nome: "Guidonia Montecelio", cap: "00012", provincia: "RM" },
  { nome: "Velletri", cap: "00049", provincia: "RM" },
  { nome: "Frascati", cap: "00044", provincia: "RM" },
  { nome: "Anzio", cap: "00042", provincia: "RM" },
  { nome: "Nettuno", cap: "00048", provincia: "RM" },
  { nome: "Pomezia", cap: "00071", provincia: "RM" },
  { nome: "Formia", cap: "04023", provincia: "LT" },
  { nome: "Terracina", cap: "04019", provincia: "LT" },
  { nome: "Gaeta", cap: "04024", provincia: "LT" },
  { nome: "Fondi", cap: "04022", provincia: "LT" },
  { nome: "Aprilia", cap: "04011", provincia: "LT" },
  { nome: "Cassino", cap: "03043", provincia: "FR" },
  { nome: "Sora", cap: "03039", provincia: "FR" },
  { nome: "Alatri", cap: "03011", provincia: "FR" },
  { nome: "Fiuggi", cap: "03014", provincia: "FR" },
  { nome: "Civita Castellana", cap: "01033", provincia: "VT" },
  { nome: "Viterbo", cap: "01100", provincia: "VT" },
  { nome: "Tarquinia", cap: "01016", provincia: "VT" },
  { nome: "Orte", cap: "01028", provincia: "VT" },
  { nome: "Giulianova", cap: "64021", provincia: "TE" },
  { nome: "Roseto degli Abruzzi", cap: "64026", provincia: "TE" },
  { nome: "Atri", cap: "64032", provincia: "TE" },
  { nome: "Montesilvano", cap: "65015", provincia: "PE" },
  { nome: "Francavilla al Mare", cap: "66023", provincia: "CH" },
  { nome: "Ortona", cap: "66026", provincia: "CH" },
  { nome: "Lanciano", cap: "66034", provincia: "CH" },
  { nome: "Vasto", cap: "66054", provincia: "CH" },
  { nome: "Sulmona", cap: "67039", provincia: "AQ" },
  { nome: "Avezzano", cap: "67051", provincia: "AQ" },
  { nome: "Celano", cap: "67043", provincia: "AQ" },
  { nome: "Venafro", cap: "86079", provincia: "IS" },
  { nome: "Termoli", cap: "86039", provincia: "CB" },
  { nome: "Larino", cap: "86035", provincia: "CB" },
  { nome: "Torre del Greco", cap: "80059", provincia: "NA" },
  { nome: "Portici", cap: "80055", provincia: "NA" },
  { nome: "Ercolano", cap: "80056", provincia: "NA" },
  { nome: "Castellammare di Stabia", cap: "80053", provincia: "NA" },
  { nome: "Sorrento", cap: "80067", provincia: "NA" },
  { nome: "Pozzuoli", cap: "80078", provincia: "NA" },
  { nome: "Ischia", cap: "80077", provincia: "NA" },
  { nome: "Capri", cap: "80073", provincia: "NA" },
  { nome: "Nola", cap: "80035", provincia: "NA" },
  { nome: "Pompei", cap: "80045", provincia: "NA" },
  { nome: "Aversa", cap: "81031", provincia: "CE" },
  { nome: "Maddaloni", cap: "81024", provincia: "CE" },
  { nome: "Marcianise", cap: "81025", provincia: "CE" },
  { nome: "Mondragone", cap: "81034", provincia: "CE" },
  { nome: "Cava de' Tirreni", cap: "84013", provincia: "SA" },
  { nome: "Nocera Inferiore", cap: "84014", provincia: "SA" },
  { nome: "Scafati", cap: "84018", provincia: "SA" },
  { nome: "Battipaglia", cap: "84091", provincia: "SA" },
  { nome: "Eboli", cap: "84025", provincia: "SA" },
  { nome: "Agropoli", cap: "84043", provincia: "SA" },
  { nome: "Amalfi", cap: "84011", provincia: "SA" },
  { nome: "Positano", cap: "84017", provincia: "SA" },
  { nome: "Ravello", cap: "84010", provincia: "SA" },
  { nome: "Ariano Irpino", cap: "83031", provincia: "AV" },
  { nome: "Altamura", cap: "70022", provincia: "BA" },
  { nome: "Molfetta", cap: "70056", provincia: "BA" },
  { nome: "Bitonto", cap: "70032", provincia: "BA" },
  { nome: "Bisceglie", cap: "76011", provincia: "BT" },
  { nome: "Trani", cap: "76125", provincia: "BT" },
  { nome: "Corato", cap: "70033", provincia: "BA" },
  { nome: "Monopoli", cap: "70043", provincia: "BA" },
  { nome: "Conversano", cap: "70014", provincia: "BA" },
  { nome: "Putignano", cap: "70017", provincia: "BA" },
  { nome: "Gioia del Colle", cap: "70023", provincia: "BA" },
  { nome: "Nardò", cap: "73048", provincia: "LE" },
  { nome: "Galatina", cap: "73013", provincia: "LE" },
  { nome: "Gallipoli", cap: "73014", provincia: "LE" },
  { nome: "Maglie", cap: "73024", provincia: "LE" },
  { nome: "Otranto", cap: "73028", provincia: "LE" },
  { nome: "Manduria", cap: "74024", provincia: "TA" },
  { nome: "Grottaglie", cap: "74023", provincia: "TA" },
  { nome: "Massafra", cap: "74016", provincia: "TA" },
  { nome: "Martina Franca", cap: "74015", provincia: "TA" },
  { nome: "Francavilla Fontana", cap: "72021", provincia: "BR" },
  { nome: "Ostuni", cap: "72017", provincia: "BR" },
  { nome: "Fasano", cap: "72015", provincia: "BR" },
  { nome: "San Giovanni Rotondo", cap: "71013", provincia: "FG" },
  { nome: "Manfredonia", cap: "71043", provincia: "FG" },
  { nome: "Cerignola", cap: "71042", provincia: "FG" },
  { nome: "Lucera", cap: "71036", provincia: "FG" },
  { nome: "San Severo", cap: "71016", provincia: "FG" },
  { nome: "Vieste", cap: "71019", provincia: "FG" },
  { nome: "Melfi", cap: "85025", provincia: "PZ" },
  { nome: "Lauria", cap: "85044", provincia: "PZ" },
  { nome: "Policoro", cap: "75025", provincia: "MT" },
  { nome: "Lamezia Terme", cap: "88046", provincia: "CZ" },
  { nome: "Soverato", cap: "88068", provincia: "CZ" },
  { nome: "Locri", cap: "89044", provincia: "RC" },
  { nome: "Siderno", cap: "89048", provincia: "RC" },
  { nome: "Gioia Tauro", cap: "89013", provincia: "RC" },
  { nome: "Tropea", cap: "89861", provincia: "VV" },
  { nome: "Pizzo", cap: "89812", provincia: "VV" },
  { nome: "Rossano", cap: "87067", provincia: "CS" },
  { nome: "Corigliano Calabro", cap: "87064", provincia: "CS" },
  { nome: "Paola", cap: "87027", provincia: "CS" },
  { nome: "Amantea", cap: "87032", provincia: "CS" },
  { nome: "Cefalù", cap: "90015", provincia: "PA" },
  { nome: "Monreale", cap: "90046", provincia: "PA" },
  { nome: "Bagheria", cap: "90011", provincia: "PA" },
  { nome: "Termini Imerese", cap: "90018", provincia: "PA" },
  { nome: "Partinico", cap: "90047", provincia: "PA" },
  { nome: "Alcamo", cap: "91011", provincia: "TP" },
  { nome: "Mazara del Vallo", cap: "91026", provincia: "TP" },
  { nome: "Castelvetrano", cap: "91022", provincia: "TP" },
  { nome: "Sciacca", cap: "92019", provincia: "AG" },
  { nome: "Licata", cap: "92027", provincia: "AG" },
  { nome: "Niscemi", cap: "93015", provincia: "CL" },
  { nome: "Gela", cap: "93012", provincia: "CL" },
  { nome: "Piazza Armerina", cap: "94015", provincia: "EN" },
  { nome: "Taormina", cap: "98039", provincia: "ME" },
  { nome: "Milazzo", cap: "98057", provincia: "ME" },
  { nome: "Barcellona Pozzo di Gotto", cap: "98051", provincia: "ME" },
  { nome: "Patti", cap: "98066", provincia: "ME" },
  { nome: "Giardini-Naxos", cap: "98035", provincia: "ME" },
  { nome: "Acireale", cap: "95024", provincia: "CT" },
  { nome: "Caltagirone", cap: "95041", provincia: "CT" },
  { nome: "Paternò", cap: "95047", provincia: "CT" },
  { nome: "Augusta", cap: "96011", provincia: "SR" },
  { nome: "Noto", cap: "96017", provincia: "SR" },
  { nome: "Avola", cap: "96012", provincia: "SR" },
  { nome: "Modica", cap: "97015", provincia: "RG" },
  { nome: "Vittoria", cap: "97019", provincia: "RG" },
  { nome: "Comiso", cap: "97013", provincia: "RG" },
  { nome: "Scicli", cap: "97018", provincia: "RG" },
  { nome: "Alghero", cap: "07041", provincia: "SS" },
  { nome: "Porto Torres", cap: "07046", provincia: "SS" },
  { nome: "Olbia", cap: "07026", provincia: "SS" },
  { nome: "Tempio Pausania", cap: "07029", provincia: "SS" },
  { nome: "Ozieri", cap: "07014", provincia: "SS" },
  { nome: "Dorgali", cap: "08022", provincia: "NU" },
  { nome: "Siniscola", cap: "08029", provincia: "NU" },
  { nome: "Macomer", cap: "08015", provincia: "NU" },
  { nome: "Quartu Sant'Elena", cap: "09045", provincia: "CA" },
  { nome: "Selargius", cap: "09047", provincia: "CA" },
  { nome: "Assemini", cap: "09032", provincia: "CA" },
  { nome: "Villacidro", cap: "09039", provincia: "SU" },
  { nome: "Sanluri", cap: "09025", provincia: "SU" },
  { nome: "Guspini", cap: "09036", provincia: "SU" },
  { nome: "Cabras", cap: "09072", provincia: "OR" },
  { nome: "Bosa", cap: "08013", provincia: "OR" },
  { nome: "Tortolì", cap: "08048", provincia: "NU" },
  { nome: "Lanusei", cap: "08045", provincia: "NU" },
  { nome: "Sinnai", cap: "09048", provincia: "CA" },
  { nome: "Dolianova", cap: "09041", provincia: "CA" },
  { nome: "Sestu", cap: "09028", provincia: "CA" },
  { nome: "Monserrato", cap: "09042", provincia: "CA" },
  { nome: "Elmas", cap: "09030", provincia: "CA" },
  { nome: "Capoterra", cap: "09012", provincia: "CA" },
  { nome: "Sarroch", cap: "09018", provincia: "CA" },
  { nome: "Pula", cap: "09010", provincia: "CA" },
  { nome: "Domus de Maria", cap: "09010", provincia: "CA" },
  { nome: "Teulada", cap: "09019", provincia: "CA" },
  { nome: "Villaputzu", cap: "09040", provincia: "CA" },
  { nome: "Muravera", cap: "09043", provincia: "CA" },
  { nome: "Castiadas", cap: "09040", provincia: "CA" },
  { nome: "San Vito", cap: "09040", provincia: "CA" },
  { nome: "Villasimius", cap: "09049", provincia: "CA" },
  { nome: "Costa Smeralda", cap: "07020", provincia: "SS" },
  { nome: "Arzachena", cap: "07021", provincia: "SS" },
  { nome: "Porto Cervo", cap: "07020", provincia: "SS" },
  { nome: "Cannigione", cap: "07020", provincia: "SS" },
  { nome: "Palau", cap: "07020", provincia: "SS" },
  { nome: "Santa Teresa Gallura", cap: "07028", provincia: "SS" },
  { nome: "La Maddalena", cap: "07024", provincia: "SS" },
  { nome: "Stintino", cap: "07040", provincia: "SS" },
  { nome: "Castelsardo", cap: "07031", provincia: "SS" },
  { nome: "Valledoria", cap: "07039", provincia: "SS" },
  { nome: "Budoni", cap: "08020", provincia: "SS" },
  { nome: "San Teodoro", cap: "08020", provincia: "SS" },
  { nome: "Golfo Aranci", cap: "07020", provincia: "SS" },
  { nome: "Loiri Porto San Paolo", cap: "07020", provincia: "SS" },
  { nome: "Abbiategrasso", cap: "20081", provincia: "MI" },
  { nome: "Acqui Terme", cap: "15011", provincia: "AL" },
  { nome: "Adria", cap: "45011", provincia: "RO" },
  { nome: "Afragola", cap: "80021", provincia: "NA" },
  { nome: "Agrate Brianza", cap: "20864", provincia: "MB" },
  { nome: "Albano Laziale", cap: "00041", provincia: "RM" },
  { nome: "Albenga", cap: "17031", provincia: "SV" },
  { nome: "Albino", cap: "24021", provincia: "BG" },
  { nome: "Albisola Superiore", cap: "17013", provincia: "SV" },
  { nome: "Alcamo", cap: "91011", provincia: "TP" },
  { nome: "Altamura", cap: "70022", provincia: "BA" },
  { nome: "Angri", cap: "84012", provincia: "SA" },
  { nome: "Anzio", cap: "00042", provincia: "RM" },
  { nome: "Aprilia", cap: "04011", provincia: "LT" },
  { nome: "Arcore", cap: "20862", provincia: "MB" },
  { nome: "Arese", cap: "20020", provincia: "MI" },
  { nome: "Arona", cap: "28041", provincia: "NO" },
  { nome: "Arzano", cap: "80022", provincia: "NA" },
  { nome: "Arzignano", cap: "36071", provincia: "VI" },
  { nome: "Augusta", cap: "96011", provincia: "SR" },
  { nome: "Aversa", cap: "81031", provincia: "CE" },
  { nome: "Avezzano", cap: "67051", provincia: "AQ" },
  { nome: "Bagheria", cap: "90011", provincia: "PA" },
  { nome: "Barcellona Pozzo di Gotto", cap: "98051", provincia: "ME" },
  { nome: "Bassano del Grappa", cap: "36061", provincia: "VI" },
  { nome: "Battipaglia", cap: "84091", provincia: "SA" },
  { nome: "Bellaria-Igea Marina", cap: "47814", provincia: "RN" },
  { nome: "Bitonto", cap: "70032", provincia: "BA" },
  { nome: "Bollate", cap: "20021", provincia: "MI" },
  { nome: "Borgomanero", cap: "28021", provincia: "NO" },
  { nome: "Bra", cap: "12042", provincia: "CN" },
  { nome: "Bracciano", cap: "00062", provincia: "RM" },
  { nome: "Brugherio", cap: "20861", provincia: "MB" },
  { nome: "Bussolengo", cap: "37012", provincia: "VR" },
  { nome: "Cairo Montenotte", cap: "17014", provincia: "SV" },
  { nome: "Caltagirone", cap: "95041", provincia: "CT" },
  { nome: "Camaiore", cap: "55041", provincia: "LU" },
  { nome: "Campi Bisenzio", cap: "50013", provincia: "FI" },
  { nome: "Campobasso", cap: "86100", provincia: "CB" },
  { nome: "Canosa di Puglia", cap: "76012", provincia: "BT" },
  { nome: "Cantù", cap: "22063", provincia: "CO" },
  { nome: "Capannori", cap: "55012", provincia: "LU" },
  { nome: "Carate Brianza", cap: "20841", provincia: "MB" },
  { nome: "Cardito", cap: "80024", provincia: "NA" },
  { nome: "Carini", cap: "90044", provincia: "PA" },
  { nome: "Carmagnola", cap: "10022", provincia: "TO" },
  { nome: "Caronno Pertusella", cap: "21042", provincia: "VA" },
  { nome: "Carpi", cap: "41012", provincia: "MO" },
  { nome: "Casale Monferrato", cap: "15033", provincia: "AL" },
  { nome: "Casalnuovo di Napoli", cap: "80013", provincia: "NA" },
  { nome: "Casaluce", cap: "81030", provincia: "CE" },
  { nome: "Casamassima", cap: "70010", provincia: "BA" },
  { nome: "Casandrino", cap: "80025", provincia: "NA" },
  { nome: "Casavatore", cap: "80020", provincia: "NA" },
  { nome: "Cascina", cap: "56021", provincia: "PI" },
  { nome: "Caselette", cap: "10040", provincia: "TO" },
  { nome: "Casorate Sempione", cap: "21011", provincia: "VA" },
  { nome: "Cassano d'Adda", cap: "20062", provincia: "MI" },
  { nome: "Cassano Magnago", cap: "21012", provincia: "VA" },
  { nome: "Castel Maggiore", cap: "40013", provincia: "BO" },
  { nome: "Castel San Giovanni", cap: "29015", provincia: "PC" },
  { nome: "Castel San Pietro Terme", cap: "40024", provincia: "BO" },
  { nome: "Castel Volturno", cap: "81030", provincia: "CE" },
  { nome: "Castelfidardo", cap: "60022", provincia: "AN" },
  { nome: "Castelfiorentino", cap: "50051", provincia: "FI" },
  { nome: "Castelfranco Emilia", cap: "41013", provincia: "MO" },
  { nome: "Castelfranco Veneto", cap: "31033", provincia: "TV" },
  { nome: "Castellammare del Golfo", cap: "91014", provincia: "TP" },
  { nome: "Castellammare di Stabia", cap: "80053", provincia: "NA" },
  { nome: "Castellanza", cap: "21053", provincia: "VA" },
  { nome: "Castelvetrano", cap: "91022", provincia: "TP" },
  { nome: "Castenaso", cap: "40055", provincia: "BO" },
  { nome: "Castiglione delle Stiviere", cap: "46043", provincia: "MN" },
  { nome: "Cava de' Tirreni", cap: "84013", provincia: "SA" },
  { nome: "Ceccano", cap: "03023", provincia: "FR" },
  { nome: "Celano", cap: "67043", provincia: "AQ" },
  { nome: "Cento", cap: "44042", provincia: "FE" },
  { nome: "Cerignola", cap: "71042", provincia: "FG" },
  { nome: "Cernusco sul Naviglio", cap: "20063", provincia: "MI" },
  { nome: "Cerveteri", cap: "00052", provincia: "RM" },
  { nome: "Cesano Boscone", cap: "20090", provincia: "MI" },
  { nome: "Cesano Maderno", cap: "20811", provincia: "MB" },
  { nome: "Chiari", cap: "25032", provincia: "BS" },
  { nome: "Chieri", cap: "10023", provincia: "TO" },
  { nome: "Chioggia", cap: "30015", provincia: "VE" },
  { nome: "Ciampino", cap: "00043", provincia: "RM" },
  { nome: "Cinisello Balsamo", cap: "20092", provincia: "MI" },
  { nome: "Cisterna di Latina", cap: "04012", provincia: "LT" },
  { nome: "Città di Castello", cap: "06012", provincia: "PG" },
  { nome: "Civita Castellana", cap: "01033", provincia: "VT" },
  { nome: "Civitanova Marche", cap: "62012", provincia: "MC" },
  { nome: "Civitavecchia", cap: "00053", provincia: "RM" },
  { nome: "Codogno", cap: "26845", provincia: "LO" },
  { nome: "Colle di Val d'Elsa", cap: "53034", provincia: "SI" },
  { nome: "Colleferro", cap: "00034", provincia: "RM" },
  { nome: "Collegno", cap: "10093", provincia: "TO" },
  { nome: "Cologno Monzese", cap: "20093", provincia: "MI" },
  { nome: "Comacchio", cap: "44022", provincia: "FE" },
  { nome: "Concorezzo", cap: "20863", provincia: "MB" },
  { nome: "Conegliano", cap: "31015", provincia: "TV" },
  { nome: "Copertino", cap: "73043", provincia: "LE" },
  { nome: "Corato", cap: "70033", provincia: "BA" },
  { nome: "Corbetta", cap: "20011", provincia: "MI" },
  { nome: "Corciano", cap: "06073", provincia: "PG" },
  { nome: "Corigliano-Rossano", cap: "87064", provincia: "CS" },
  { nome: "Cornaredo", cap: "20010", provincia: "MI" },
  { nome: "Cornedo Vicentino", cap: "36073", provincia: "VI" },
  { nome: "Corsico", cap: "20094", provincia: "MI" },
  { nome: "Cortemaggiore", cap: "29016", provincia: "PC" },
  { nome: "Crema", cap: "26013", provincia: "CR" },
  { nome: "Crevalcore", cap: "40014", provincia: "BO" },
  { nome: "Dalmine", cap: "24044", provincia: "BG" },
  { nome: "Darfo Boario Terme", cap: "25047", provincia: "BS" },
  { nome: "Desenzano del Garda", cap: "25015", provincia: "BS" },
  { nome: "Desio", cap: "20832", provincia: "MB" },
  { nome: "Duino Aurisina", cap: "34011", provincia: "TS" },
  { nome: "Eboli", cap: "84025", provincia: "SA" },
  { nome: "Empoli", cap: "50053", provincia: "FI" },
  { nome: "Erba", cap: "22036", provincia: "CO" },
  { nome: "Ercolano", cap: "80056", provincia: "NA" },
  { nome: "Erice", cap: "91016", provincia: "TP" },
  { nome: "Fabriano", cap: "60044", provincia: "AN" },
  { nome: "Faenza", cap: "48018", provincia: "RA" },
  { nome: "Fagnano Olona", cap: "21054", provincia: "VA" },
  { nome: "Falconara Marittima", cap: "60015", provincia: "AN" },
  { nome: "Fano", cap: "61032", provincia: "PU" },
  { nome: "Fasano", cap: "72015", provincia: "BR" },
  { nome: "Favara", cap: "92026", provincia: "AG" },
  { nome: "Fermo", cap: "63900", provincia: "FM" },
  { nome: "Fidenza", cap: "43036", provincia: "PR" },
  { nome: "Fiesole", cap: "50014", provincia: "FI" },
  { nome: "Figline e Incisa Valdarno", cap: "50063", provincia: "FI" },
  { nome: "Finale Ligure", cap: "17024", provincia: "SV" },
  { nome: "Fiorano Modenese", cap: "41042", provincia: "MO" },
  { nome: "Fisciano", cap: "84084", provincia: "SA" },
  { nome: "Fiumicino", cap: "00054", provincia: "RM" },
  { nome: "Floridia", cap: "96014", provincia: "SR" },
  { nome: "Follonica", cap: "58022", provincia: "GR" },
  { nome: "Fondi", cap: "04022", provincia: "LT" },
  { nome: "Formia", cap: "04023", provincia: "LT" },
  { nome: "Formigine", cap: "41043", provincia: "MO" },
  { nome: "Fossano", cap: "12045", provincia: "CN" },
  { nome: "Francavilla al Mare", cap: "66023", provincia: "CH" },
  { nome: "Francavilla Fontana", cap: "72021", provincia: "BR" },
  { nome: "Frascati", cap: "00044", provincia: "RM" },
  { nome: "Frattamaggiore", cap: "80027", provincia: "NA" },
  { nome: "Fucecchio", cap: "50054", provincia: "FI" },
  { nome: "Gaeta", cap: "04024", provincia: "LT" },
  { nome: "Galatina", cap: "73013", provincia: "LE" },
  { nome: "Gallarate", cap: "21013", provincia: "VA" },
  { nome: "Gallipoli", cap: "73014", provincia: "LE" },
  { nome: "Garbagnate Milanese", cap: "20024", provincia: "MI" },
  { nome: "Gardone Val Trompia", cap: "25063", provincia: "BS" },
  { nome: "Gattinara", cap: "13045", provincia: "VC" },
  { nome: "Gavardo", cap: "25085", provincia: "BS" },
  { nome: "Gela", cap: "93012", provincia: "CL" },
  { nome: "Ghedi", cap: "25016", provincia: "BS" },
  { nome: "Giarre", cap: "95014", provincia: "CT" },
  { nome: "Gioia del Colle", cap: "70023", provincia: "BA" },
  { nome: "Gioia Tauro", cap: "89013", provincia: "RC" },
  { nome: "Giovinazzo", cap: "70054", provincia: "BA" },
  { nome: "Giulianova", cap: "64021", provincia: "TE" },
  { nome: "Gorizia", cap: "34170", provincia: "GO" },
  { nome: "Gragnano", cap: "80054", provincia: "NA" },
  { nome: "Granarolo dell'Emilia", cap: "40057", provincia: "BO" },
  { nome: "Gravina in Puglia", cap: "70024", provincia: "BA" },
  { nome: "Grugliasco", cap: "10095", provincia: "TO" },
  { nome: "Gualdo Tadino", cap: "06023", provincia: "PG" },
  { nome: "Guidonia Montecelio", cap: "00012", provincia: "RM" },
  { nome: "Iglesias", cap: "09016", provincia: "SU" },
  { nome: "Imola", cap: "40026", provincia: "BO" },
  { nome: "Impruneta", cap: "50023", provincia: "FI" },
  { nome: "Ischia", cap: "80077", provincia: "NA" },
  { nome: "Iseo", cap: "25049", provincia: "BS" },
  { nome: "Isola del Liri", cap: "03036", provincia: "FR" },
  { nome: "Ivrea", cap: "10015", provincia: "TO" },
  { nome: "Jesolo", cap: "30016", provincia: "VE" },
  { nome: "Lainate", cap: "20020", provincia: "MI" },
  { nome: "Lanciano", cap: "66034", provincia: "CH" },
  { nome: "Lamezia Terme", cap: "88046", provincia: "CZ" },
  { nome: "Landriano", cap: "27015", provincia: "PV" },
  { nome: "Lanuvio", cap: "00040", provincia: "RM" },
  { nome: "Lastra a Signa", cap: "50055", provincia: "FI" },
  { nome: "Latiano", cap: "72022", provincia: "BR" },
  { nome: "Lavagna", cap: "16033", provincia: "GE" },
  { nome: "Legnago", cap: "37045", provincia: "VR" },
  { nome: "Legnano", cap: "20025", provincia: "MI" },
  { nome: "Lentini", cap: "96016", provincia: "SR" },
  { nome: "Leonforte", cap: "94013", provincia: "EN" },
  { nome: "Licata", cap: "92027", provincia: "AG" },
  { nome: "Lido di Camaiore", cap: "55041", provincia: "LU" },
  { nome: "Limbiate", cap: "20812", provincia: "MB" },
  { nome: "Lissone", cap: "20851", provincia: "MB" },
  { nome: "Locri", cap: "89044", provincia: "RC" },
  { nome: "Lonigo", cap: "36045", provincia: "VI" },
  { nome: "Loreto", cap: "60025", provincia: "AN" },
  { nome: "Lugo", cap: "48022", provincia: "RA" },
  { nome: "Lumezzane", cap: "25065", provincia: "BS" },
  { nome: "Macerata", cap: "62100", provincia: "MC" },
  { nome: "Maddaloni", cap: "81024", provincia: "CE" },
  { nome: "Magenta", cap: "20013", provincia: "MI" },
  { nome: "Malo", cap: "36034", provincia: "VI" },
  { nome: "Manduria", cap: "74024", provincia: "TA" },
  { nome: "Manerbio", cap: "25025", provincia: "BS" },
  { nome: "Manfredonia", cap: "71043", provincia: "FG" },
  { nome: "Marcianise", cap: "81025", provincia: "CE" },
  { nome: "Marcon", cap: "30020", provincia: "VE" },
  { nome: "Margherita di Savoia", cap: "76016", provincia: "BT" },
  { nome: "Mariano Comense", cap: "22066", provincia: "CO" },
  { nome: "Marigliano", cap: "80034", provincia: "NA" },
  { nome: "Marino", cap: "00047", provincia: "RM" },
  { nome: "Martina Franca", cap: "74015", provincia: "TA" },
  { nome: "Matera", cap: "75100", provincia: "MT" },
  { nome: "Mazara del Vallo", cap: "91026", provincia: "TP" },
  { nome: "Meda", cap: "20821", provincia: "MB" },
  { nome: "Melegnano", cap: "20077", provincia: "MI" },
  { nome: "Melito di Napoli", cap: "80017", provincia: "NA" },
  { nome: "Melzo", cap: "20066", provincia: "MI" },
  { nome: "Mentana", cap: "00013", provincia: "RM" },
  { nome: "Merano", cap: "39012", provincia: "BZ" },
  { nome: "Meran", cap: "39012", provincia: "BZ" },
  { nome: "Mercato San Severino", cap: "84085", provincia: "SA" },
  { nome: "Merate", cap: "23807", provincia: "LC" },
  { nome: "Mestre", cap: "30170", provincia: "VE" },
  { nome: "Mira", cap: "30034", provincia: "VE" },
  { nome: "Mirandola", cap: "41037", provincia: "MO" },
  { nome: "Mirano", cap: "30035", provincia: "VE" },
  { nome: "Misano Adriatico", cap: "47843", provincia: "RN" },
  { nome: "Misterbianco", cap: "95045", provincia: "CT" },
  { nome: "Modica", cap: "97015", provincia: "RG" },
  { nome: "Modugno", cap: "70026", provincia: "BA" },
  { nome: "Mogliano Veneto", cap: "31021", provincia: "TV" },
  { nome: "Mola di Bari", cap: "70042", provincia: "BA" },
  { nome: "Molfetta", cap: "70056", provincia: "BA" },
  { nome: "Moncalieri", cap: "10024", provincia: "TO" },
  { nome: "Mondragone", cap: "81034", provincia: "CE" },
  { nome: "Mondovì", cap: "12084", provincia: "CN" },
  { nome: "Monfalcone", cap: "34074", provincia: "GO" },
  { nome: "Monopoli", cap: "70043", provincia: "BA" },
  { nome: "Monreale", cap: "90046", provincia: "PA" },
  { nome: "Montagnana", cap: "35044", provincia: "PD" },
  { nome: "Montebelluna", cap: "31044", provincia: "TV" },
  { nome: "Montecatini-Terme", cap: "51016", provincia: "PT" },
  { nome: "Montecchio Maggiore", cap: "36075", provincia: "VI" },
  { nome: "Montecorvino Rovella", cap: "84096", provincia: "SA" },
  { nome: "Montegrotto Terme", cap: "35036", provincia: "PD" },
  { nome: "Montemurlo", cap: "59013", provincia: "PO" },
  { nome: "Montepulciano", cap: "53045", provincia: "SI" },
  { nome: "Monterotondo", cap: "00015", provincia: "RM" },
  { nome: "Montevarchi", cap: "52025", provincia: "AR" },
  { nome: "Monticello Brianza", cap: "23876", provincia: "LC" },
  { nome: "Montichiari", cap: "25018", provincia: "BS" },
  { nome: "Montignoso", cap: "54038", provincia: "MS" },
  { nome: "Monza", cap: "20900", provincia: "MB" },
  { nome: "Morbegno", cap: "23017", provincia: "SO" },
  { nome: "Motta di Livenza", cap: "31045", provincia: "TV" },
  { nome: "Muggiò", cap: "20835", provincia: "MB" },
  { nome: "Mugnano di Napoli", cap: "80018", provincia: "NA" },
  { nome: "Nardò", cap: "73048", provincia: "LE" },
  { nome: "Nerviano", cap: "20014", provincia: "MI" },
  { nome: "Nettuno", cap: "00048", provincia: "RM" },
  { nome: "Nichelino", cap: "10042", provincia: "TO" },
  { nome: "Nicosia", cap: "94014", provincia: "EN" },
  { nome: "Niscemi", cap: "93015", provincia: "CL" },
  { nome: "Noci", cap: "70015", provincia: "BA" },
  { nome: "Nocera Inferiore", cap: "84014", provincia: "SA" },
  { nome: "Nocera Superiore", cap: "84015", provincia: "SA" },
  { nome: "Noicattaro", cap: "70016", provincia: "BA" },
  { nome: "Nola", cap: "80035", provincia: "NA" },
  { nome: "Nonantola", cap: "41015", provincia: "MO" },
  { nome: "Norcia", cap: "06046", provincia: "PG" },
  { nome: "Noto", cap: "96017", provincia: "SR" },
  { nome: "Nova Milanese", cap: "20834", provincia: "MB" },
  { nome: "Novate Milanese", cap: "20026", provincia: "MI" },
  { nome: "Novi Ligure", cap: "15067", provincia: "AL" },
  { nome: "Olgiate Comasco", cap: "22077", provincia: "CO" },
  { nome: "Omegna", cap: "28887", provincia: "VB" },
  { nome: "Opera", cap: "20090", provincia: "MI" },
  { nome: "Orbassano", cap: "10043", provincia: "TO" },
  { nome: "Oria", cap: "72024", provincia: "BR" },
  { nome: "Oristano", cap: "09170", provincia: "OR" },
  { nome: "Orzinuovi", cap: "25034", provincia: "BS" },
  { nome: "Osimo", cap: "60027", provincia: "AN" },
  { nome: "Ospitaletto", cap: "25035", provincia: "BS" },
  { nome: "Ostuni", cap: "72017", provincia: "BR" },
  { nome: "Ottaviano", cap: "80044", provincia: "NA" },
  { nome: "Ovada", cap: "15076", provincia: "AL" },
  { nome: "Ozieri", cap: "07014", provincia: "SS" },
  { nome: "Pachino", cap: "96018", provincia: "SR" },
  { nome: "Palagiano", cap: "74019", provincia: "TA" },
  { nome: "Palazzolo sull'Oglio", cap: "25036", provincia: "BS" },
  { nome: "Palestrina", cap: "00036", provincia: "RM" },
  { nome: "Palmi", cap: "89015", provincia: "RC" },
  { nome: "Parabiago", cap: "20015", provincia: "MI" },
  { nome: "Partinico", cap: "90047", provincia: "PA" },
  { nome: "Paterno", cap: "95047", provincia: "CT" },
  { nome: "Paternò", cap: "95047", provincia: "CT" },
  { nome: "Paullo", cap: "20067", provincia: "MI" },
  { nome: "Pedara", cap: "95030", provincia: "CT" },
  { nome: "Penne", cap: "65017", provincia: "PE" },
  { nome: "Pergine Valsugana", cap: "38057", provincia: "TN" },
  { nome: "Pescantina", cap: "37026", provincia: "VR" },
  { nome: "Pessano con Bornago", cap: "20060", provincia: "MI" },
  { nome: "Piazzola sul Brenta", cap: "35016", provincia: "PD" },
  { nome: "Pieve di Soligo", cap: "31053", provincia: "TV" },
  { nome: "Pioltello", cap: "20096", provincia: "MI" },
  { nome: "Piombino", cap: "57025", provincia: "LI" },
  { nome: "Piossasco", cap: "10045", provincia: "TO" },
  { nome: "Pisticci", cap: "75015", provincia: "MT" },
  { nome: "Poggibonsi", cap: "53036", provincia: "SI" },
  { nome: "Poggio a Caiano", cap: "59016", provincia: "PO" },
  { nome: "Polistena", cap: "89024", provincia: "RC" },
  { nome: "Pomigliano d'Arco", cap: "80038", provincia: "NA" },
  { nome: "Pompei", cap: "80045", provincia: "NA" },
  { nome: "Pontedera", cap: "56025", provincia: "PI" },
  { nome: "Pontecagnano Faiano", cap: "84098", provincia: "SA" },
  { nome: "Ponticelli", cap: "80147", provincia: "NA" },
  { nome: "Porcia", cap: "33080", provincia: "PN" },
  { nome: "Porto Recanati", cap: "62017", provincia: "MC" },
  { nome: "Porto San Giorgio", cap: "63822", provincia: "FM" },
  { nome: "Porto Sant'Elpidio", cap: "63821", provincia: "FM" },
  { nome: "Porto Torres", cap: "07046", provincia: "SS" },
  { nome: "Portogruaro", cap: "30026", provincia: "VE" },
  { nome: "Portici", cap: "80055", provincia: "NA" },
  { nome: "Pozzallo", cap: "97016", provincia: "RG" },
  { nome: "Pozzuoli", cap: "80078", provincia: "NA" },
  { nome: "Preganziol", cap: "31022", provincia: "TV" },
  { nome: "Priverno", cap: "04015", provincia: "LT" },
  { nome: "Putignano", cap: "70017", provincia: "BA" },
  { nome: "Qualiano", cap: "80019", provincia: "NA" },
  { nome: "Quarrata", cap: "51039", provincia: "PT" },
  { nome: "Quarto", cap: "80010", provincia: "NA" },
  { nome: "Quattromiglia", cap: "87036", provincia: "CS" },
  { nome: "Racconigi", cap: "12035", provincia: "CN" },
  { nome: "Randazzo", cap: "95036", provincia: "CT" },
  { nome: "Rapallo", cap: "16035", provincia: "GE" },
  { nome: "Recanati", cap: "62019", provincia: "MC" },
  { nome: "Reggio Calabria", cap: "89100", provincia: "RC" },
  { nome: "Reggiolo", cap: "42046", provincia: "RE" },
  { nome: "Rende", cap: "87036", provincia: "CS" },
  { nome: "Rezzato", cap: "25086", provincia: "BS" },
  { nome: "Rho", cap: "20017", provincia: "MI" },
  { nome: "Ribera", cap: "92016", provincia: "AG" },
  { nome: "Riccione", cap: "47838", provincia: "RN" },
  { nome: "Rieti", cap: "02100", provincia: "RI" },
  { nome: "Riva del Garda", cap: "38066", provincia: "TN" },
  { nome: "Rivoli", cap: "10098", provincia: "TO" },
  { nome: "Romano di Lombardia", cap: "24058", provincia: "BG" },
  { nome: "Rosarno", cap: "89025", provincia: "RC" },
  { nome: "Roseto degli Abruzzi", cap: "64026", provincia: "TE" },
  { nome: "Rossano", cap: "87067", provincia: "CS" },
  { nome: "Rovereto", cap: "38068", provincia: "TN" },
  { nome: "Rovigo", cap: "45100", provincia: "RO" },
  { nome: "Ruvo di Puglia", cap: "70037", provincia: "BA" },
  { nome: "Sacile", cap: "33077", provincia: "PN" },
  { nome: "Salerno", cap: "84100", provincia: "SA" },
  { nome: "Salsomaggiore Terme", cap: "43039", provincia: "PR" },
  { nome: "Saluzzo", cap: "12037", provincia: "CN" },
  { nome: "Sammichele di Bari", cap: "70010", provincia: "BA" },
  { nome: "San Benedetto del Tronto", cap: "63074", provincia: "AP" },
  { nome: "San Bonifacio", cap: "37047", provincia: "VR" },
  { nome: "San Cataldo", cap: "93017", provincia: "CL" },
  { nome: "San Cesareo", cap: "00030", provincia: "RM" },
  { nome: "San Donà di Piave", cap: "30027", provincia: "VE" },
  { nome: "San Donato Milanese", cap: "20097", provincia: "MI" },
  { nome: "San Gavino Monreale", cap: "09037", provincia: "SU" },
  { nome: "San Giorgio a Cremano", cap: "80046", provincia: "NA" },
  { nome: "San Giorgio Ionico", cap: "74027", provincia: "TA" },
  { nome: "San Giovanni in Fiore", cap: "87055", provincia: "CS" },
  { nome: "San Giovanni in Persiceto", cap: "40017", provincia: "BO" },
  { nome: "San Giovanni la Punta", cap: "95037", provincia: "CT" },
  { nome: "San Giovanni Lupatoto", cap: "37057", provincia: "VR" },
  { nome: "San Giovanni Rotondo", cap: "71013", provincia: "FG" },
  { nome: "San Giovanni Valdarno", cap: "52027", provincia: "AR" },
  { nome: "San Giuliano Milanese", cap: "20098", provincia: "MI" },
  { nome: "San Giuliano Terme", cap: "56017", provincia: "PI" },
  { nome: "San Giuseppe Vesuviano", cap: "80047", provincia: "NA" },
  { nome: "San Lazzaro di Savena", cap: "40068", provincia: "BO" },
  { nome: "San Mauro Torinese", cap: "10099", provincia: "TO" },
  { nome: "San Miniato", cap: "56028", provincia: "PI" },
  { nome: "San Nicola la Strada", cap: "81020", provincia: "CE" },
  { nome: "San Pellegrino Terme", cap: "24016", provincia: "BG" },
  { nome: "San Pietro in Casale", cap: "40018", provincia: "BO" },
  { nome: "San Remo", cap: "18038", provincia: "IM" },
  { nome: "San Severo", cap: "71016", provincia: "FG" },
  { nome: "San Vito dei Normanni", cap: "72019", provincia: "BR" },
  { nome: "Sanremo", cap: "18038", provincia: "IM" },
  { nome: "Sant'Agata de' Goti", cap: "82019", provincia: "BN" },
  { nome: "Sant'Anastasia", cap: "80048", provincia: "NA" },
  { nome: "Sant'Antimo", cap: "80029", provincia: "NA" },
  { nome: "Sant'Arpino", cap: "81030", provincia: "CE" },
  { nome: "Santa Croce sull'Arno", cap: "56029", provincia: "PI" },
  { nome: "Santa Marinella", cap: "00058", provincia: "RM" },
  { nome: "Santa Maria a Vico", cap: "81028", provincia: "CE" },
  { nome: "Santa Maria Capua Vetere", cap: "81055", provincia: "CE" },
  { nome: "Santarcangelo di Romagna", cap: "47822", provincia: "RN" },
  { nome: "Santhià", cap: "13048", provincia: "VC" },
  { nome: "Santo Stefano di Magra", cap: "19037", provincia: "SP" },
  { nome: "Santeramo in Colle", cap: "70029", provincia: "BA" },
  { nome: "Sarno", cap: "84087", provincia: "SA" },
  { nome: "Saronno", cap: "21047", provincia: "VA" },
  { nome: "Sarzana", cap: "19038", provincia: "SP" },
  { nome: "Sassuolo", cap: "41049", provincia: "MO" },
  { nome: "Savigliano", cap: "12038", provincia: "CN" },
  { nome: "Scandicci", cap: "50018", provincia: "FI" },
  { nome: "Sciacca", cap: "92019", provincia: "AG" },
  { nome: "Scicli", cap: "97018", provincia: "RG" },
  { nome: "Segrate", cap: "20090", provincia: "MI" },
  { nome: "Senigallia", cap: "60019", provincia: "AN" },
  { nome: "Seregno", cap: "20831", provincia: "MB" },
  { nome: "Seriate", cap: "24068", provincia: "BG" },
  { nome: "Serravalle Scrivia", cap: "15069", provincia: "AL" },
  { nome: "Sessa Aurunca", cap: "81037", provincia: "CE" },
  { nome: "Sestri Levante", cap: "16039", provincia: "GE" },
  { nome: "Settimo Milanese", cap: "20019", provincia: "MI" },
  { nome: "Settimo Torinese", cap: "10036", provincia: "TO" },
  { nome: "Siderno", cap: "89048", provincia: "RC" },
  { nome: "Signa", cap: "50058", provincia: "FI" },
  { nome: "Silvi", cap: "64028", provincia: "TE" },
  { nome: "Somma Vesuviana", cap: "80049", provincia: "NA" },
  { nome: "Sora", cap: "03039", provincia: "FR" },
  { nome: "Sorrento", cap: "80067", provincia: "NA" },
  { nome: "Spilimbergo", cap: "33097", provincia: "PN" },
  { nome: "Spinea", cap: "30038", provincia: "VE" },
  { nome: "Spoleto", cap: "06049", provincia: "PG" },
  { nome: "Stezzano", cap: "24040", provincia: "BG" },
  { nome: "Sulmona", cap: "67039", provincia: "AQ" },
  { nome: "Taggia", cap: "18018", provincia: "IM" },
  { nome: "Tarquinia", cap: "01016", provincia: "VT" },
  { nome: "Taviano", cap: "73057", provincia: "LE" },
  { nome: "Terlizzi", cap: "70038", provincia: "BA" },
  { nome: "Termini Imerese", cap: "90018", provincia: "PA" },
  { nome: "Termoli", cap: "86039", provincia: "CB" },
  { nome: "Ternate", cap: "21020", provincia: "VA" },
  { nome: "Thiene", cap: "36016", provincia: "VI" },
  { nome: "Tivoli", cap: "00019", provincia: "RM" },
  { nome: "Tolentino", cap: "62029", provincia: "MC" },
  { nome: "Tolmezzo", cap: "33028", provincia: "UD" },
  { nome: "Torre Annunziata", cap: "80058", provincia: "NA" },
  { nome: "Torre del Greco", cap: "80059", provincia: "NA" },
  { nome: "Tortona", cap: "15057", provincia: "AL" },
  { nome: "Tradate", cap: "21049", provincia: "VA" },
  { nome: "Trani", cap: "76125", provincia: "BT" },
  { nome: "Trapani", cap: "91100", provincia: "TP" },
  { nome: "Tre Fontane", cap: "91010", provincia: "TP" },
  { nome: "Tremestieri Etneo", cap: "95030", provincia: "CT" },
  { nome: "Treviglio", cap: "24047", provincia: "BG" },
  { nome: "Tricase", cap: "73039", provincia: "LE" },
  { nome: "Triggiano", cap: "70019", provincia: "BA" },
  { nome: "Triggianello", cap: "70019", provincia: "BA" },
  { nome: "Trofarello", cap: "10028", provincia: "TO" },
  { nome: "Ugento", cap: "73059", provincia: "LE" },
  { nome: "Urbino", cap: "61029", provincia: "PU" },
  { nome: "Valdagno", cap: "36078", provincia: "VI" },
  { nome: "Valdobbiadene", cap: "31049", provincia: "TV" },
  { nome: "Valenza", cap: "15048", provincia: "AL" },
  { nome: "Vallecrosia", cap: "18019", provincia: "IM" },
  { nome: "Valsamoggia", cap: "40056", provincia: "BO" },
  { nome: "Vasto", cap: "66054", provincia: "CH" },
  { nome: "Velletri", cap: "00049", provincia: "RM" },
  { nome: "Venaria Reale", cap: "10078", provincia: "TO" },
  { nome: "Ventimiglia", cap: "18039", provincia: "IM" },
  { nome: "Viareggio", cap: "55049", provincia: "LU" },
  { nome: "Vigevano", cap: "27029", provincia: "PV" },
  { nome: "Vignola", cap: "41058", provincia: "MO" },
  { nome: "Vigonza", cap: "35010", provincia: "PD" },
  { nome: "Villa Literno", cap: "81039", provincia: "CE" },
  { nome: "Villa San Giovanni", cap: "89018", provincia: "RC" },
  { nome: "Villabate", cap: "90039", provincia: "PA" },
  { nome: "Villafranca di Verona", cap: "37069", provincia: "VR" },
  { nome: "Villanova d'Asti", cap: "14019", provincia: "AT" },
  { nome: "Villaricca", cap: "80010", provincia: "NA" },
  { nome: "Villorba", cap: "31020", provincia: "TV" },
  { nome: "Vimercate", cap: "20871", provincia: "MB" },
  { nome: "Vimodrone", cap: "20090", provincia: "MI" },
  { nome: "Vittoria", cap: "97019", provincia: "RG" },
  { nome: "Vittorio Veneto", cap: "31029", provincia: "TV" },
  { nome: "Voghera", cap: "27058", provincia: "PV" },
  { nome: "Volterra", cap: "56048", provincia: "PI" },
  { nome: "Zagarolo", cap: "00039", provincia: "RM" },
  { nome: "Zola Predosa", cap: "40069", provincia: "BO" },
  { nome: "Bressanone", cap: "39042", provincia: "BZ" },
  { nome: "Brixen", cap: "39042", provincia: "BZ" },
  { nome: "Brunico", cap: "39031", provincia: "BZ" },
  { nome: "Bruneck", cap: "39031", provincia: "BZ" },
  { nome: "Vipiteno", cap: "39049", provincia: "BZ" },
  { nome: "Sterzing", cap: "39049", provincia: "BZ" },
  { nome: "Laives", cap: "39055", provincia: "BZ" },
  { nome: "Leifers", cap: "39055", provincia: "BZ" },
  { nome: "Appiano sulla Strada del Vino", cap: "39057", provincia: "BZ" },
  { nome: "Eppan an der Weinstraße", cap: "39057", provincia: "BZ" },
  { nome: "Caldaro sulla Strada del Vino", cap: "39052", provincia: "BZ" },
  { nome: "Kaltern an der Weinstraße", cap: "39052", provincia: "BZ" },
  { nome: "Lana", cap: "39011", provincia: "BZ" },
  { nome: "Silandro", cap: "39028", provincia: "BZ" },
  { nome: "Schlanders", cap: "39028", provincia: "BZ" },
  { nome: "Chiusa", cap: "39043", provincia: "BZ" },
  { nome: "Klausen", cap: "39043", provincia: "BZ" },
  { nome: "Ortisei", cap: "39046", provincia: "BZ" },
  { nome: "Sankt Ulrich", cap: "39046", provincia: "BZ" },
  { nome: "Selva di Val Gardena", cap: "39048", provincia: "BZ" },
  { nome: "Wolkenstein", cap: "39048", provincia: "BZ" },
  { nome: "Corvara in Badia", cap: "39033", provincia: "BZ" },
  { nome: "Corvara", cap: "39033", provincia: "BZ" },
];

export function findCittaInfo(nome: string): CittaInfo | undefined {
  const normalized = nome.trim().toLowerCase();
  return CITTA_ITALIANE.find(c => c.nome.toLowerCase() === normalized);
}

export function searchCitta(query: string): CittaInfo[] {
  if (!query || query.length < 2) return [];
  const normalized = query.trim().toLowerCase();
  return CITTA_ITALIANE.filter(c => 
    c.nome.toLowerCase().includes(normalized)
  ).slice(0, 10);
}
